# workflows 
names: hello

on: 
  workflow_dispatch: 
# job
jobs: 
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to everyone 
        run: echo "Hello dosto"


# steps

#actions
